### ISSUE TITLE
Solarthermal interface

### ISSUE THREAD

**Issue by Blackeye55** [deg0nz/MMM-EnergyMonitor#3]
As well as generating electricity from panels on the roof, there are many thermal energy generation installations nowadays that are managed/monitored digitally, and that therefore generate displayable information. In my case, it's a Buderus/Bosch system with a corresponding My Buderus app ... there are of course other manufacturers. 
Could you consider providing a module to extract available data such as the current panel temperature, kW generated today, total kW generated this month/since installation, current water tank temperature, and maybe the relationship fossil (oil,gas)/solar energy used.
PM me for details of the system installed here.

**Comment by deg0nz** [comment]
I need more information here. This sounds like a dedicated new module to me.
`MMM-EnergyMonitor` has the focus of showing electric power flow. Maybe the naming here is suboptimal...

What data would you like to monitor exactly?

**Comment by Blackeye55** [comment]
As I mentioned in the second paragraph, the Buderus system (here with a KM200 interface) calculates the kWh of energy obtained from the solar panels on the roof. This is stored for each of the last 14 days, and also totalled since the system was first started. This is very interesting information that I would like to display on my magic mirror. 
The module only has to extract more information from the system than the current KM200 module already does - all the sensors are already connected to the bus and the data has been 'processed' - it just needs reading out. Unfortunately I am not skilled enough to adapt/write this module myself.

**Comment by deg0nz** [comment]
Ok, so if I understand you correctly, you need a module that fetches data from the Buderus system like [MMM-Fronius2](https://github.com/deg0nz/MMM-Fronius2), which then sends data to MMM-EnergyMonitor?

If that is the case, I'm sorry to disappoint you. I have many other projects in my pipeline. I just don't have time to provide that. 
Since I also don't have access to such a system to try around and access its interfaces, this will add another hurdle to jump over when developing such a module.

I suggest you ask the community in the MagicMirror forums and make a request there. Maybe someone has time and wants to build this for you. Please check out the forum: https://forum.magicmirror.builders/category/9/requests.

I'm closing this issue. Feel free to open it again if I got something wrong.
